project_name: rancher-driver

before:
  hooks:
    - go mod tidy
builds:
  - main: ./bin/main.go
    env:
      - CGO_ENABLED=0
      - GO111MODULE=on
    mod_timestamp: '{{ .CommitTimestamp }}'
    flags:
      - -trimpath
      - -mod=vendor
    goos:
      - windows
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    binary: 'docker-machine-driver-ionoscloud'
archives:
  - name_template: '{{ .ProjectName }}-{{ .Version }}-{{ .Os }}-{{ .Arch }}'
    format_overrides:
      - goos: windows
        format: zip
    files: [include-only-the-binary*]
    wrap_in_directory: false
checksum:
  name_template: '{{ .ProjectName }}-{{ .Version }}-SHA256SUMS'
  algorithm: sha256
release:
# If you want to manually examine the release before its live, uncomment this line:
# draft: true
changelog:
  skip: true
